name: uc-initrd
base: core20
version: '0'
version-script: echo "20-lk-$(apt-cache search --names-only "linux-image-5.4.0.*-generic" | sort | tail -1 | awk -F '-' '{print $3"-"$4}')"
summary: Ubuntu Core initrd
description: |
  Ubuntu Core initrd

grade: stable
confinement: strict

parts:
    initrd:
        plugin: nil
        override-build: |
            # UC20 initrd builder only supports native build!
            # build UC20 initrd
            if [ -z "$(which ubuntu-core-initramfs)" ]; then
                sudo add-apt-repository -y ppa:snappy-dev/image
                sudo apt-get install -y ubuntu-core-initramfs
            fi
            # first prepare empty kernel modules structure. We want *vanilla* initrd anyway
            kernel_version="5.4.0"
            modules_path_release="lib/modules/${kernel_version}"
            mkdir -p ${modules_path_release}
            touch ${modules_path_release}/modules.builtin
            touch ${modules_path_release}/modules.order
            depmod -b . ${kernel_version}
            # we need to run tool as root to get rigt permissions
            mkdir -p clean-initrd
            sudo ubuntu-core-initramfs create-initrd \
                --kerneldir ${modules_path_release} \
                --kernelver ${kernel_version} \
                --output ${SNAPCRAFT_PART_INSTALL}/initrd
            sudo chown ${USER}:${USER} ${SNAPCRAFT_PART_INSTALL}/initrd*
        organize:
            "initrd-*": vanilla-initrd.img
        prime:
            - -*

    snap-bootstrap:
        plugin: nil
        build-snaps:
            - go
        override-pull: |
            mkdir -p go/src/github.com/snapcore
            # https://github.com/snapcore/snapd.git \
            git clone https://github.com/kubiko/snapd.git \
                      -b uc20-debug \
                      go/src/github.com/snapcore/snapd
        override-build: |
            GOPATH=${SNAPCRAFT_PART_BUILD}/go
            export GOPATH
            cd ${SNAPCRAFT_PART_BUILD}/go/src/github.com/snapcore/snapd
            ./get-deps.sh
            # CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 go build \
            #        -o ${SNAPCRAFT_PART_INSTALL}/snap-bootstrap ./cmd/snap-bootstrap/
            CGO_ENABLED=1 go build -o ${SNAPCRAFT_PART_INSTALL}/snap-bootstrap ./cmd/snap-bootstrap
        prime:
            - -*

    initrd-repack:
        plugin: nil
        after:
            - snap-bootstrap
            - initrd
        override-build: |
            # replace custom snap-bootstrap in initrd
            echo "Replacing snap-bootstrap with custom one"
            unmkinitramfs ${SNAPCRAFT_STAGE}/vanilla-initrd.img .
            rm -rf usr/lib/modules/*
            # check if initrd is nested (amd64)
            [ -d main ] && main="main/"
            cp ${SNAPCRAFT_STAGE}/snap-bootstrap ${main}usr/lib/snapd/snap-bootstrap
            find . | cpio --create --quiet --format='newc' --owner=0:0 | lz4 -l -7 > ${SNAPCRAFT_PART_INSTALL}/initrd.img

build-packages:
    - software-properties-common
    - initramfs-tools-core
    - build-essential
    - gcc
    - lz4
