name: uc-initrd
base: core20
version: '0'
version-script: echo "20-splash-$(apt-cache search --names-only "linux-image-5.4.0.*-generic" | sort | tail -1 | awk -F '-' '{print $3"-"$4}')"
summary: Ubuntu Core initrd
description: |
  Ubuntu Core initrd

grade: stable
confinement: strict

parts:
    initrd:
        plugin: nil
        override-build: |
            # UC20 initrd builder only supports native build!
            # build UC20 initrd
            if [ -z "$(which ubuntu-core-initramfs)" ]; then
                sudo add-apt-repository -y ppa:snappy-dev/image
                sudo apt-get install -y ubuntu-core-initramfs
            fi
            # first prepare empty kernel modules structure. We want *vanilla* initrd anyway
            kernel_version="5.4.0"
            modules_path_release="lib/modules/${kernel_version}"
            mkdir -p ${modules_path_release}
            touch ${modules_path_release}/modules.builtin
            touch ${modules_path_release}/modules.order
            depmod -b . ${kernel_version}
            # we need to run tool as root to get rigt permissions
            mkdir -p clean-initrd
            sudo ubuntu-core-initramfs create-initrd \
                --kerneldir ${modules_path_release} \
                --kernelver ${kernel_version} \
                --output ${SNAPCRAFT_PART_INSTALL}/initrd
            sudo chown ${USER}:${USER} ${SNAPCRAFT_PART_INSTALL}/initrd*
        organize:
            "initrd-*": vanilla-initrd.img
        prime:
            - -*

    psplash:
        plugin: autotools
        source: https://github.com/kubiko/ubuntu-psplash.git
        autotools-configure-parameters:
            - --build=${SNAPCRAFT_ARCH_TRIPLET}
            - --host=${SNAPCRAFT_ARCH_TRIPLET}
            - --prefix=/usr
            - --with-systemd
            - --with-font=ubuntu
            - CC=${SNAPCRAFT_ARCH_TRIPLET}-gcc
            - LIBS="-lsystemd"
        override-pull: |
            snapcraftctl pull
            sed -i 's/POKY_IMG/CORE_IMG/g' psplash.c
            otf2bdf -p 22 -r 75 -v \
              $(ls /usr/share/fonts/truetype/*/Ubuntu-R.ttf) \
              -o ubuntu.bdf || res=$?
            if [ "$res" != "8" ]; then
              echo "Unexpected exit code from otf2bdf, should be 8"
              exit 1
            fi
            bdftobogl ubuntu.bdf > ubuntu-font.h
            sed -i \
                -e 's/#include "bogl\.h"/#include "psplash\.h"/g' \
                -e 's/struct bogl_font font_ubuntu/PSplashFont ubuntu_font/g' \
                ubuntu-font.h
            ln -sf core_orange_hex.png psplash-core.png
            ./make-image-header.sh psplash-core.png CORE
            sed -i \
                -e 's/psplash-poky-img.h/psplash-core-img.h/g' \
                Makefile.am psplash.c
        override-build: |
            snapcraftctl build
            install -m 644 -T -D \
                psplash-start.service \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/psplash-start.service
            install -m 644 -T -D \
                psplash-systemd-initrd.service \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/psplash-systemd-initrd.service
             install -m 644 -T -D \
                psplash-systemd-setup.service \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/psplash-systemd-setup.service
            mkdir -p \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/basic.target.wants \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/run-mnt-data.mount.wants
            ln -sf \
                ../psplash-start.service \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/basic.target.wants/psplash-start.service
            ln -sf \
                ../psplash-systemd-initrd.service \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/basic.target.wants/psplash-systemd-initrd.service
            ln -sf \
                ../psplash-systemd-setup.service \
                ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/run-mnt-data.mount.wants/psplash-systemd-setup.service
        prime:
            - -*

    initrd-repack:
        plugin: nil
        after:
            - psplash
            - initrd
        override-build: |
            # remove any kernel modules added here
            unmkinitramfs ${SNAPCRAFT_STAGE}/vanilla-initrd.img .
            rm -rf usr/lib/modules/*
            # check if initrd is nested (amd64)
            if [ -d main ]; then
              cp -r ${SNAPCRAFT_STAGE}/usr main/
            else
              cp -r ${SNAPCRAFT_STAGE}/usr .
            fi
            find . | cpio --create --quiet --format='newc' --owner=0:0 | lz4 -l -7 > ${SNAPCRAFT_PART_INSTALL}/initrd.img

build-packages:
    - build-essential
    - initramfs-tools-core
    - fonts-ubuntu
    - gcc
    - lz4
    - libbogl-dev
    - libgdk-pixbuf2.0-bin
    - libsystemd-dev
    - otf2bdf
    - software-properties-common
