name: uc-initrd
base: core22
version: '0'
version-script: echo "20-edge-$(grep version parts/snap-bootstrap/install/meta.snapd/snap.yaml | awk '{print $2}' | awk -F '.' '{ OFS = "." }{ $NF = ""; print $0}'| sed 's/.$//')"
summary: Ubuntu Core initrd
description: |
  Ubuntu Core initrd

grade: stable
confinement: strict

parts:
    initrd:
        plugin: nil
        override-build: |
            # UC20 initrd builder only supports native build!
            # build UC20 initrd
            if [ -z "$(which ubuntu-core-initramfs)" ]; then
                sudo add-apt-repository -y ppa:snappy-dev/image
                sudo apt-get install -y ubuntu-core-initramfs
            fi
            # first prepare empty kernel modules structure. We want *vanilla* initrd anyway
            kernel_version="5.15.0"
            modules_path_release="lib/modules/${kernel_version}"
            mkdir -p ${modules_path_release}
            touch ${modules_path_release}/modules.builtin
            touch ${modules_path_release}/modules.order
            depmod -b . ${kernel_version}
            # we need to run tool as root to get rigt permissions
            mkdir -p clean-initrd
            sudo ubuntu-core-initramfs create-initrd \
                --kerneldir ${modules_path_release} \
                --kernelver ${kernel_version} \
                --output ${SNAPCRAFT_PART_INSTALL}/initrd
            sudo chown ${USER}:${USER} ${SNAPCRAFT_PART_INSTALL}/initrd*
        organize:
            "initrd-*": vanilla-initrd.img
        prime:
            - -*

    snap-bootstrap:
        plugin: nil
        stage-snaps:
            - snapd/latest/edge
        organize:
            usr/lib/snapd/snap-bootstrap: snap-bootstrap
        stage:
            - snap-bootstrap
        prime:
            - -*

    initrd-repack:
        plugin: nil
        after:
            - snap-bootstrap
            - initrd
        override-build: |
            # replace custom snap-bootstrap in initrd
            echo "Replacing snap-bootstrap with custom one"
            unmkinitramfs ${SNAPCRAFT_STAGE}/vanilla-initrd.img .
            rm -rf usr/lib/modules/*
            # check if initrd is nested (amd64)
            if [ -d main ]; then
              cp ${SNAPCRAFT_STAGE}/snap-bootstrap main/usr/lib/snapd/snap-bootstrap
            else
              cp ${SNAPCRAFT_STAGE}/snap-bootstrap usr/lib/snapd/snap-bootstrap
            fi
            find . | cpio --create --quiet --format='newc' --owner=0:0 | lz4 -l -7 > ${SNAPCRAFT_PART_INSTALL}/initrd.img

build-packages:
    - software-properties-common
    - initramfs-tools-core
    - lz4
